In [1]:
import numpy as np

A = np.array([2.4, 6.7, 7.9])
print("Array A has a shape of:", A.shape) # shape returns a tuple of rows, cols 
print("Array A has dimension:", A.ndim) # ndim returns an integer representing the dimensions


Array A has a shape of: (3,)
Array A has dimension: 1


In [2]:
import numpy as np

A = np.array([[2.4, 6.7, 7.9]])
print("Array A has a shape of:", A.shape) # shape returns a tuple of rows, cols 
print("Array A has dimension:", A.ndim) # ndim returns an integer representing the dimensions


Array A has a shape of: (1, 3)
Array A has dimension: 2


In [3]:
A = np.array([ [2.4, 6.7, 7.9], # double brackets, so this is row 0
             [1.1, -7.8, -0.7], # row 1
             [4.1, 12.3, 4.8]]) # row 2
A[1,0] # index A at row 1, col 0 (can also index using chained indexing: A[1][0]) 


1.1

In [4]:
A[0,:] # grab all of row 0


array([2.4, 6.7, 7.9])

In [5]:
A[:,0] # grab all of col 0


array([2.4, 1.1, 4.1])

In [6]:
A = np.array([
[11, 12, 13, 14, 15], # row 0
[21, 22, 23, 24, 25], # row 1
[31, 32, 33, 34, 35], # row 2
[41, 42, 43, 44, 45], # row 3
[51, 52, 53, 54, 55]]) # row 4

A[:3, 2:] # first argument :3 slices rows 0-2, second argument 2: slices cols 2-end of array


array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

In [7]:
A[3:, :]


array([[41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55]])

In [9]:
A[:, 4:]


array([[15],
       [25],
       [35],
       [45],
       [55]])

In [12]:
A[::2, ::3] # ::2 starts at row 0 through the end of the array, skipping over every other row, and ::3 starts at col 0 through the end of the array, grabbing every third entry


array([[11, 14],
       [31, 34],
       [51, 54]])

In [13]:
X=np.arange(28)
X


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [14]:
print(X.shape)
print(X.ndim)


(28,)
1


In [15]:
X.reshape(4,7)


array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [16]:
X.reshape(2,14)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [17]:
X.reshape(5,5)


ValueError: cannot reshape array of size 28 into shape (5,5)